# Generated by Django 5.0.1 on 2024-01-26 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.", regex='^\\+?998?\\d{9,13}$')])),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password1', models.CharField(max_length=128)),
                ('password2', models.CharField(max_length=128)),
            ],
        ),
    ]
